import axios from 'axios';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  const handleSubmit = async (e) => {
    e.preventDefault();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Claim Discord Developer Badge - Under Ctrl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={handleSubmit}>
          <label htmlFor="tokenField">Bot Token</label>
          <input
            type="text"
            id="tokenField"
            placeholder="Enter your bot's token"
          />
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  );
}
